source /home/ee450/Desktop/Kernel2/kernel/main/gdt.gdb
source /home/ee450/Desktop/Kernel2/kernel/mm/pagetable.gdb
source /home/ee450/Desktop/Kernel2/kernel/mm/page.py
source /home/ee450/Desktop/Kernel2/kernel/mm/memcheck.py
source /home/ee450/Desktop/Kernel2/kernel/mm/slab.py
source /home/ee450/Desktop/Kernel2/kernel/proc/kthread.gdb
source /home/ee450/Desktop/Kernel2/kernel/proc/proc.py
source /home/ee450/Desktop/Kernel2/kernel/util/debug.py
source /home/ee450/Desktop/Kernel2/kernel/util/list.py
source /home/ee450/Desktop/Kernel2/kernel/vm/vmmap.gdb
